version: 2
jobs:
  build:
    working_directory: /go/src/github.com/segmentio/{{ .Name }}

    docker:
      - image: golang
        environment:
          ECR_ENABLED: True

    steps:
      - checkout

      - restore_cache:
          key: deps-{{ `{{ checksum "Gopkg.lock" }}` }}

      - run:
          name: Configure netrc
          command: |
            echo "machine github.com login $GH_LOGIN" > ~/.netrc

      - setup_remote_docker:
          reusable: true

      - run:
          name: ECR Login
          command: |
            curl -O https://bootstrap.pypa.io/get-pip.py && python get-pip.py
            pip install awscli==1.11.76
            $(aws ecr get-login --region $AWS_REGION)

      - run:
          name: Dependencies
          command: |
            go get -u github.com/golang/dep/cmd/dep
            make deps

      - run:
          name: Test
          command: |
            make test

      - save_cache:
          key: deps-{{ `{{ checksum "Gopkg.lock" }}` }}
          paths:
            - vendor/

      - run:
          name: Deployment
          command: |
            make release

      - store_artifacts:
          path: .run
          destination: trebuchet
