#!/bin/bash

VERSION=$1

# when we have a semver string, let's tag major/minor as a range
# ie: 1.2.3 => 1.x + 1.2.x
if [[ "$VERSION" =~ ^v?[0-9]+(\.[0-9]+){2}$ ]]; then
  echo `echo $VERSION | cut -d. -f1`.x   # major
  echo `echo $VERSION | cut -d. -f1-2`.x # minor
  # patch not needed since it's the same as $VERSION
fi

# always output the original input
echo $VERSION
